CELLS_INFO = {
    'MEDITERRANEAN_AVENUE': {
        'PRICE': 60,
        'PRICE_PER_HOUSE': 50,
        'RENT': 2,
        'RENT_ONE_HOUSE': 10,
        'RENT_TWO_HOUSES': 30,
        'RENT_THREE_HOUSES': 90,
        'RENT_FOUR_HOUSES': 160,
        'RENT_HOTEL': 250,
        'MORTGAGE': 30,
    },
    'BALTIC_AVENUE': {
        'PRICE': 60,
        'PRICE_PER_HOUSE': 50,
        'RENT': 4,
        'RENT_ONE_HOUSE': 20,
        'RENT_TWO_HOUSES': 60,
        'RENT_THREE_HOUSES': 180,
        'RENT_FOUR_HOUSES': 320,
        'RENT_HOTEL': 450,
        'MORTGAGE': 30,
    },
    'ORIENTAL_AVENUE': {
        'PRICE': 100,
        'PRICE_PER_HOUSE': 50,
        'RENT': 6,
        'RENT_ONE_HOUSE': 30,
        'RENT_TWO_HOUSES': 90,
        'RENT_THREE_HOUSES': 270,
        'RENT_FOUR_HOUSES': 400,
        'RENT_HOTEL': 550,
        'MORTGAGE': 50,
    },
    'VERMONT_AVENUE': {
        'PRICE': 100,
        'PRICE_PER_HOUSE': 50,
        'RENT': 6,
        'RENT_ONE_HOUSE': 30,
        'RENT_TWO_HOUSES': 90,
        'RENT_THREE_HOUSES': 270,
        'RENT_FOUR_HOUSES': 400,
        'RENT_HOTEL': 550,
        'MORTGAGE': 50,
    },
    'CONNECTICUT_AVENUE': {
        'PRICE': 120,
        'PRICE_PER_HOUSE': 50,
        'RENT': 8,
        'RENT_ONE_HOUSE': 40,
        'RENT_TWO_HOUSES': 100,
        'RENT_THREE_HOUSES': 300,
        'RENT_FOUR_HOUSES': 450,
        'RENT_HOTEL': 600,
        'MORTGAGE': 60,
    },
    'STCHARLES_PLACE': {
        'PRICE': 140,
        'PRICE_PER_HOUSE': 100,
        'RENT': 10,
        'RENT_ONE_HOUSE': 50,
        'RENT_TWO_HOUSES': 150,
        'RENT_THREE_HOUSES': 450,
        'RENT_FOUR_HOUSES': 625,
        'RENT_HOTEL': 750,
        'MORTGAGE': 70,
    },
    'STATES_AVENUE': {
        'PRICE': 140,
        'PRICE_PER_HOUSE': 100,
        'RENT': 10,
        'RENT_ONE_HOUSE': 50,
        'RENT_TWO_HOUSES': 150,
        'RENT_THREE_HOUSES': 450,
        'RENT_FOUR_HOUSES': 625,
        'RENT_HOTEL': 750,
        'MORTGAGE': 70,
    },
    'VIRGINIA_AVENUE': {
        'PRICE': 160,
        'PRICE_PER_HOUSE': 100,
        'RENT': 12,
        'RENT_ONE_HOUSE': 60,
        'RENT_TWO_HOUSES': 180,
        'RENT_THREE_HOUSES': 500,
        'RENT_FOUR_HOUSES': 700,
        'RENT_HOTEL': 900,
        'MORTGAGE': 80,
    },
    'STJAMES_PLACE': {
        'PRICE': 180,
        'PRICE_PER_HOUSE': 100,
        'RENT': 14,
        'RENT_ONE_HOUSE': 70,
        'RENT_TWO_HOUSES': 200,
        'RENT_THREE_HOUSES': 550,
        'RENT_FOUR_HOUSES': 750,
        'RENT_HOTEL': 950,
        'MORTGAGE': 90,
    },
    'TENNESSEE_AVENUE': {
        'PRICE': 180,
        'PRICE_PER_HOUSE': 100,
        'RENT': 14,
        'RENT_ONE_HOUSE': 70,
        'RENT_TWO_HOUSES': 200,
        'RENT_THREE_HOUSES': 550,
        'RENT_FOUR_HOUSES': 750,
        'RENT_HOTEL': 950,
        'MORTGAGE': 90,
    },
    'NEWYORK_AVENUE': {
        'PRICE': 200,
        'PRICE_PER_HOUSE': 100,
        'RENT': 16,
        'RENT_ONE_HOUSE': 80,
        'RENT_TWO_HOUSES': 220,
        'RENT_THREE_HOUSES': 600,
        'RENT_FOUR_HOUSES': 800,
        'RENT_HOTEL': 1000,
        'MORTGAGE': 100,
    },
    'KENTUCKY_AVENUE': {
        'PRICE': 220,
        'PRICE_PER_HOUSE': 150,
        'RENT': 18,
        'RENT_ONE_HOUSE': 90,
        'RENT_TWO_HOUSES': 250,
        'RENT_THREE_HOUSES': 700,
        'RENT_FOUR_HOUSES': 875,
        'RENT_HOTEL': 1050,
        'MORTGAGE': 110,
    },
    'IDIANA_AVENUE': {
        'PRICE': 220,
        'PRICE_PER_HOUSE': 150,
        'RENT': 18,
        'RENT_ONE_HOUSE': 90,
        'RENT_TWO_HOUSES': 250,
        'RENT_THREE_HOUSES': 700,
        'RENT_FOUR_HOUSES': 875,
        'RENT_HOTEL': 1050,
        'MORTGAGE': 110,
    },
    'ILLINOIS_AVENUE': {
        'PRICE': 240,
        'PRICE_PER_HOUSE': 150,
        'RENT': 20,
        'RENT_ONE_HOUSE': 100,
        'RENT_TWO_HOUSES': 300,
        'RENT_THREE_HOUSES': 750,
        'RENT_FOUR_HOUSES': 925,
        'RENT_HOTEL': 1100,
        'MORTGAGE': 120,
    },
    'ATLANTIC_AVENUE': {
        'PRICE': 260,
        'PRICE_PER_HOUSE': 150,
        'RENT': 22,
        'RENT_ONE_HOUSE': 110,
        'RENT_TWO_HOUSES': 330,
        'RENT_THREE_HOUSES': 800,
        'RENT_FOUR_HOUSES': 975,
        'RENT_HOTEL': 1150,
        'MORTGAGE': 130,
    },
    'VENTNOR_AVENUE': {
        'PRICE': 260,
        'PRICE_PER_HOUSE': 150,
        'RENT': 22,
        'RENT_ONE_HOUSE': 110,
        'RENT_TWO_HOUSES': 330,
        'RENT_THREE_HOUSES': 800,
        'RENT_FOUR_HOUSES': 975,
        'RENT_HOTEL': 1150,
        'MORTGAGE': 130,
    },
    'MARVIN_GARDENS': {
        'PRICE': 280,
        'PRICE_PER_HOUSE': 150,
        'RENT': 24,
        'RENT_ONE_HOUSE': 120,
        'RENT_TWO_HOUSES': 360,
        'RENT_THREE_HOUSES': 850,
        'RENT_FOUR_HOUSES': 1025,
        'RENT_HOTEL': 1200,
        'MORTGAGE': 140,
    },
    'PACIFIC_AVENUE': {
        'PRICE': 300,
        'PRICE_PER_HOUSE': 200,
        'RENT': 26,
        'RENT_ONE_HOUSE': 130,
        'RENT_TWO_HOUSES': 390,
        'RENT_THREE_HOUSES': 900,
        'RENT_FOUR_HOUSES': 1100,
        'RENT_HOTEL': 1275,
        'MORTGAGE': 150,
    },
    'NORTH_CAROLINA_AVENUE': {
        'PRICE': 300,
        'PRICE_PER_HOUSE': 200,
        'RENT': 26,
        'RENT_ONE_HOUSE': 130,
        'RENT_TWO_HOUSES': 390,
        'RENT_THREE_HOUSES': 900,
        'RENT_FOUR_HOUSES': 1100,
        'RENT_HOTEL': 1275,
        'MORTGAGE': 150,
    },
    'PENNSYLVANIA_AVENUE': {
        'PRICE': 320,
        'PRICE_PER_HOUSE': 200,
        'RENT': 28,
        'RENT_ONE_HOUSE': 150,
        'RENT_TWO_HOUSES': 450,
        'RENT_THREE_HOUSES': 1000,
        'RENT_FOUR_HOUSES': 1200,
        'RENT_HOTEL': 1400,
        'MORTGAGE': 160,
    },
    'PARK_PLACE': {
        'PRICE': 350,
        'PRICE_PER_HOUSE': 200,
        'RENT': 35,
        'RENT_ONE_HOUSE': 175,
        'RENT_TWO_HOUSES': 500,
        'RENT_THREE_HOUSES': 1100,
        'RENT_FOUR_HOUSES': 1300,
        'RENT_HOTEL': 1500,
        'MORTGAGE': 175,
    },
    'BOARD_WALK': {
        'PRICE': 400,
        'PRICE_PER_HOUSE': 200,
        'RENT': 50,
        'RENT_ONE_HOUSE': 200,
        'RENT_TWO_HOUSES': 600,
        'RENT_THREE_HOUSES': 1400,
        'RENT_FOUR_HOUSES': 1700,
        'RENT_HOTEL': 2000,
        'MORTGAGE': 200,
    },
}